apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallet-db
  namespace: wallet
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: wallet-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: csnp-platform/lab06/wallet-db
        property: username
    - secretKey: password
      remoteRef:
        key: csnp-platform/lab06/wallet-db
        property: password

