apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: csnp-lab
  namespace: argocd
spec:
  description: CSNP Lab workloads only
  sourceRepos:
    - REPLACE_REPOSITORY_URL
  destinations:
    - namespace: wallet
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

